Lektion-6/Fixxo/Models/ContactFormModel.cs
using J2N.Text;
using System.ComponentModel.DataAnnotations;

namespace Fixxo.Models
{
	public class ContactFormModel
	{
		[Required]
		public string Name { get; set; } = null!;

		[Required]
		[EmailAddress]
		public string Email { get; set; } = null!;

		[Required]
		public string Comment { get; set; } = null!;

		public string? RedirectUrl { get; set; } = "/";
	}
}

Lektion-6/Fixxo/Models/ProductModel.cs
namespace Fixxo.Models
{
    public class ProductModel
    {
        public Guid Id { get; set; } = Guid.NewGuid();
        public string Name { get; set; } = null!;
        public string Description { get; set; } = null!;
        public decimal Price { get; set; }

        public string? RedirectUrl { get; set; } = "/";
    }
}

Lektion-6/Fixxo/Controllers/ContactsController.cs
using Fixxo.Models;
using Fixxo.Services;
using Microsoft.AspNetCore.Mvc;
using Umbraco.Cms.Core.Cache;
using Umbraco.Cms.Core.Logging;
using Umbraco.Cms.Core.Routing;
using Umbraco.Cms.Core.Services;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Infrastructure.Persistence;
using Umbraco.Cms.Web.Website.Controllers;

namespace Fixxo.Controllers
{
	public class ContactsController : SurfaceController
	{
		public ContactsController(IUmbracoContextAccessor umbracoContextAccessor, IUmbracoDatabaseFactory databaseFactory, ServiceContext services, AppCaches appCaches, IProfilingLogger profilingLogger, IPublishedUrlProvider publishedUrlProvider) : base(umbracoContextAccessor, databaseFactory, services, appCaches, profilingLogger, publishedUrlProvider)
		{
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Contacts([Bind(Prefix = "contactFormModel")]ContactFormModel model)
		{
			if (!ModelState.IsValid)
				return RedirectToCurrentUmbracoUrl();

			using var mail = new MailSender("", "", 587, "", "");
			mail.SendAsync(model.Email, $"Vi har mottagit din kontaktförfrågan", "Hej vi har mottagit din kontaktförfrågan. Vi återkommer till dig så snart vi kan.").ConfigureAwait(false);
            mail.SendAsync("", $"{model.Name} har skickat en kontaktförfrågan", model.Comment).ConfigureAwait(false);

            if (!string.IsNullOrWhiteSpace(model.RedirectUrl))
				return Redirect(Url.IsLocalUrl(model.RedirectUrl) 
					? model.RedirectUrl 
					: CurrentPage!.AncestorOrSelf(1)!.Url(PublishedUrlProvider));

			return RedirectToCurrentUmbracoUrl();

		}
	}
}

Lektion-6/Fixxo/Controllers/ProductsController.cs
using Fixxo.Contexts;
using Fixxo.Models;
using Fixxo.Services;
using Microsoft.AspNetCore.Mvc;
using Umbraco.Cms.Core.Cache;
using Umbraco.Cms.Core.Logging;
using Umbraco.Cms.Core.Routing;
using Umbraco.Cms.Core.Services;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Infrastructure.Persistence;
using Umbraco.Cms.Web.Website.Controllers;

namespace Fixxo.Controllers
{
    public class ProductsController : SurfaceController
    {
        private readonly DataContext _context;

        public ProductsController(IUmbracoContextAccessor umbracoContextAccessor, IUmbracoDatabaseFactory databaseFactory, ServiceContext services, AppCaches appCaches, IProfilingLogger profilingLogger, IPublishedUrlProvider publishedUrlProvider, DataContext context) : base(umbracoContextAccessor, databaseFactory, services, appCaches, profilingLogger, publishedUrlProvider)
        {
            _context = context;
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index([Bind(Prefix = "productModel")] ProductModel model)
        {
            if (!ModelState.IsValid)
                return RedirectToCurrentUmbracoUrl();

            // save to database
            _context.Add(model);
            await _context.SaveChangesAsync();


            if (!string.IsNullOrWhiteSpace(model.RedirectUrl))
                return Redirect(Url.IsLocalUrl(model.RedirectUrl)
                    ? model.RedirectUrl
                    : CurrentPage!.AncestorOrSelf(1)!.Url(PublishedUrlProvider));

            return RedirectToCurrentUmbracoUrl();
        }
    }
}

Lektion-6/Fixxo/Views/AddProduct.cshtml
@using Fixxo.Models;
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.AddProduct>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
    Layout = "Layout.cshtml";
    ViewData["PageTitle"] = @Model.Value("pageTitle");
    ViewData["PageDescription"] = @Model.Value("pageDescription");

    foreach (var keyword in @Model.PageKeywords)
    {
        ViewData["PageKeywords"] += $"{keyword},";
    }

    var productModel = new ProductModel();
}

<form asp-controller="Products" asp-action="Index" method="post" noValidate>

    @Html.AntiForgeryToken()

    <div asp-validation-summary="ModelOnly" class="errorMessage"></div>

    <div>
        <input asp-for="@productModel.Name" placeholder="ProductName Name" />
        <div class="errorMessage">
            <span asp-validation-for="@productModel.Name"></span>
        </div>
    </div>
    <div>
        <input asp-for="@productModel.Price" placeholder="Product Price" />
        <div class="errorMessage">
            <span asp-validation-for="@productModel.Price"></span>
        </div>
    </div>
    <div class="textarea">
        <textarea asp-for="@productModel.Description" placeholder="Description"></textarea>
        <div class="errorMessage">
            <span asp-validation-for="@productModel.Description"></span>
        </div>
    </div>
    <div class="formBtn">
        <button type="submit" class="btn btn-theme">Add Product</button>
    </div>
</form>

Lektion-6/Fixxo/Views/Contacts.cshtml
@using Fixxo.Models;
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.Contacts>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
    Layout = "Layout.cshtml";
    ViewData["PageTitle"] = @Model.Value("pageTitle");
    ViewData["PageDescription"] = @Model.Value("pageDescription");

    foreach (var keyword in @Model.PageKeywords)
    {
        ViewData["PageKeywords"] += $"{keyword},";
    }

    var contactFormModel = new ContactFormModel();

}

<div class="contact-us">
    <div class="google-maps">
        <iframe src="@Model.Value("googleMapsUrl")" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
    
    <section class="contact-form">
        <div class="container">            
            <div class="content text-center">
                <h2>@Model.Value("pageTitle")</h2>
            </div>
            
            <form asp-controller="Contacts" asp-action="Contacts" method="post" noValidate>

                @Html.AntiForgeryToken()

                <div asp-validation-summary="ModelOnly" class="errorMessage"></div>

                <div>
                    <input asp-for="@contactFormModel.Name" placeholder="Your Name" />
                    <div class="errorMessage">
                        <span asp-validation-for="@contactFormModel.Name"></span>
                    </div>
                </div>
                <div>
                    <input asp-for="@contactFormModel.Email" placeholder="Your Mail" />
                    <div class="errorMessage">
                        <span asp-validation-for="@contactFormModel.Email"></span>
                    </div>
                </div>
                <div class="textarea">
                    <textarea asp-for="@contactFormModel.Comment" placeholder="Comments"></textarea>
                    <div class="errorMessage">
                        <span asp-validation-for="@contactFormModel.Comment"></span>
                    </div>
                </div>
                <div class="formBtn">
                    <button type="submit" class="btn btn-theme">Post Comments</button>
                </div>
            </form>
        
        </div>
    </section>
</div>

Lektion-6/Fixxo/Views/Home.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.Home>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
	Layout = "Layout.cshtml";
	ViewData["PageTitle"] = @Model.Value("pageTitle");
	ViewData["PageDescription"] = @Model.Value("pageDescription");

	foreach (var keyword in @Model.PageKeywords)
	{
		ViewData["PageKeywords"] += $"{keyword},";
	}
}

Lektion-6/Fixxo/Views/Layout.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@{
	Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<script src="https://kit.fontawesome.com/41c8b474e2.js" crossorigin="anonymous"></script>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
	<link href="~/css/style.css" rel="stylesheet">
	<script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
	<script defer src="~/scripts/script.js"></script>

	<title>@ViewData["PageTitle"] | Fixxo.</title>
	<meta name="description" content="@ViewData["PageDescription"]">
	<meta name="keywords" content="@ViewData["PageKeywords"]">
	
</head>
<body>
    
    <partial name="Header" /> 
    
    @RenderBody()

    <partial name="Footer" />
    
</body>
</html>

Lektion-6/Fixxo/Views/Partials/Footer.cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage

<footer id="footer">
    <div class="container content">
        <div class="row">
            <div class="col-3">
                <h1>Customer Service</h1>
                <ul>
                    <li><a href="#">Help & FAQs</a></li>
                    <li><a href="#">Order Lookup</a></li>
                    <li><a href="#">Shipping & Delivery</a></li>
                    <li><a href="#">Returns</a></li>
                    <li><a href="#">Contact Us</a></li>
                </ul>
            </div>            
            <div class="col-3">
                <h1>Fixxo's Credit Card</h1>
                <ul>
                    <li><a href="#">Fixxo's Services</a></li>
                    <li><a href="#">Pay Your Credit Card Bill</a></li>
                    <li><a href="#">Cardholder Benefits</a></li>
                    <li><a href="#">Apply for Fixxo's Credit Card</a></li>
                </ul>
            </div>            
            <div class="col-3">
                <h1>Our Stores</h1>
                <ul>
                    <li><a href="#">Stores & Services</a></li>
                    <li><a href="#">Locations & Hours</a></li>
                    <li><a href="#">Store Events</a></li>
                    <li><a href="#">Catalogs</a></li>
                </ul>
            </div>            
            <div class="col-3">
                <h1>Our App</h1>
                <ul class="our-app">
                    <li><a href="#"><img class="app-icon" src="~/images/app-store-badge.png" alt=""></a></li>
                    <li><a href="#"><img class="app-icon" src="~/images/google-play-badge.png" alt=""></a></li>
                </ul>
                <ul class="socialmedia">
                    <li><a href="#"><i class="fa-brands fa-facebook-f"></i></a></li>
                    <li><a href="#"><i class="fa-brands fa-instagram"></i></a></li>
                    <li><a href="#"><i class="fa-brands fa-twitter"></i></a></li>
                    <li><a href="#"><i class="fa-brands fa-google"></i></a></li>
                    <li><a href="#"><i class="fa-brands fa-linkedin"></i></a></li>
                </ul>
            </div>            
        </div>
    </div>
    <div class="copyright">
        © @DateTime.Now.Year Fixxo. All Rights Reserved.
    </div>
</footer>

Lektion-6/Fixxo/Views/Partials/Header.cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@using Umbraco.Cms.Core
@using Umbraco.Cms.Core.Models.PublishedContent
@using Umbraco.Cms.Core.Routing
@using Umbraco.Extensions

@inject IPublishedValueFallback PublishedValueFallback
@inject IPublishedUrlProvider PublishedUrlProvider

@{ 
    var site = Model.Root();    
    var selection = site.Children.Where(x => x.IsVisible(PublishedValueFallback)).ToArray(); 
}


<nav class="navbar navbar-expand-lg">
    <div class="container">
        <a class="navbar-brand" href="@site.Url()">Fixxo.</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link @(Model.Id == site.Id ? "active" : null)" href="@site.Url()">@site.Name</a></li>
                
                @if (selection?.Length > 0)
                {
                    @foreach (var item in selection)
                    {
                        <li class="nav-item"><a class="nav-link @(item.IsAncestorOrSelf(Model) ? "active" : null)" href="@item.Url(PublishedUrlProvider)">@item.Name</a></li>
                    }
                }
            </ul>
            <ul class="navbar-shopping">
                <li class="nav-item"><a class="nav-link" href="#"><i class="fa-regular fa-search"></i></a></li>
                <li class="nav-item"><a class="nav-link" href="#"><i class="fa-regular fa-code-compare"></i></a></li>
                <li class="nav-item"><a class="nav-link" href="#"><i class="fa-regular fa-heart"></i></a></li>
                <li class="nav-item"><a class="nav-link" href="#"><i class="fa-regular fa-shopping-bag"></i></a></li>
            </ul>
        </div>
    </div>
</nav>

Lektion-6/Fixxo/Views/Partials/blockgrid/area.cshtml
@using Umbraco.Extensions
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockGridArea>

<div class="umb-block-grid__area"
     data-area-col-span="@Model.ColumnSpan"
     data-area-row-span="@Model.RowSpan"
     data-area-alias="@Model.Alias"
     style="--umb-block-grid--grid-columns: @Model.ColumnSpan;--umb-block-grid--area-column-span: @Model.ColumnSpan; --umb-block-grid--area-row-span: @Model.RowSpan;">
    @await Html.GetBlockGridItemsHtmlAsync(Model)
</div>

Lektion-6/Fixxo/Views/Partials/blockgrid/areas.cshtml
@using Umbraco.Extensions
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockGridItem>
@{
    if (Model?.Areas.Any() != true) { return; }
}

<div class="umb-block-grid__area-container"
     style="--umb-block-grid--area-grid-columns: @(Model.AreaGridColumns?.ToString() ?? Model.GridColumns?.ToString() ?? "12");">
    @foreach (var area in Model.Areas)
    {
        @await Html.GetBlockGridItemAreaHtmlAsync(area)
    }
</div>

Lektion-6/Fixxo/Views/Partials/blockgrid/default.cshtml
@using Umbraco.Extensions
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockGridModel>
@{
    if (Model?.Any() != true) { return; }
}

<div class="umb-block-grid"
     data-grid-columns="@(Model.GridColumns?.ToString() ?? "12");"
     style="--umb-block-grid--grid-columns: @(Model.GridColumns?.ToString() ?? "12");">
    @await Html.GetBlockGridItemsHtmlAsync(Model)
</div>

Lektion-6/Fixxo/Views/Partials/blockgrid/items.cshtml
@using Umbraco.Cms.Core.Models.Blocks
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<IEnumerable<BlockGridItem>>
@{
    if (Model?.Any() != true) { return; }
}

<div class="umb-block-grid__layout-container">
    @foreach (var item in Model)
    {
        
        <div
            class="umb-block-grid__layout-item"
            data-content-element-type-alias="@item.Content.ContentType.Alias"
            data-content-element-type-key="@item.Content.ContentType.Key"
            data-element-udi="@item.ContentUdi"
            data-col-span="@item.ColumnSpan"
            data-row-span="@item.RowSpan"
            style=" --umb-block-grid--item-column-span: @item.ColumnSpan; --umb-block-grid--item-row-span: @item.RowSpan; ">
            @{
                var partialViewName = "blockgrid/Components/" + item.Content.ContentType.Alias;
                try
                {
                    @await Html.PartialAsync(partialViewName, item)
                }
                catch (InvalidOperationException)
                {
                    <p>
                        <strong>Could not render component of type: @(item.Content.ContentType.Alias)</strong>
                        <br/>
                        This likely happened because the partial view <em>@partialViewName</em> could not be found.
                    </p>
                }
            }
        </div>
    }
</div>

Lektion-6/Fixxo/Views/Partials/blocklist/default.cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockListModel>
@{
    if (Model?.Any() != true) { return; }
}
<div class="umb-block-list">
    @foreach (var block in Model)
    {
        if (block?.ContentUdi == null) { continue; }
        var data = block.Content;

        @await Html.PartialAsync("blocklist/Components/" + data.ContentType.Alias, block)
    }
</div>

Lektion-6/Fixxo/Views/Partials/grid/bootstrap3-fluid.cshtml
@using System.Web
@using Microsoft.AspNetCore.Html
@using Newtonsoft.Json.Linq
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<dynamic>

@*
    Razor helpers located at the bottom of this file
*@

@if (Model is JObject && Model?.sections is not null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;

    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections)
            {
                <div class="grid-section">
                    @foreach (var row in section.rows)
                    {
                        renderRow(row);
                    }
                </div>
            }
        }
        else
        {
            <div class="row clearfix">
                @foreach (var sec in Model.sections)
                {
                    <div class="grid-section">
                        <div class="col-md-@sec.grid column">
                            @foreach (var row in sec.rows)
                            {
                                renderRow(row);
                            }
                        </div>
                    </div>
                }
            </div>
        }
    </div>
}

@functions{

    private async Task renderRow(dynamic row)
    {
        <div @RenderElementAttributes(row)>
            <div class="row clearfix">
                @foreach (var area in row.areas)
                {
                    <div class="col-md-@area.grid column">
                        <div @RenderElementAttributes(area)>
                            @foreach (var control in area.controls)
                            {
                                if (control?.editor?.view != null)
                                {
                                    <text>@await Html.PartialAsync("grid/editors/base", (object)control)</text>
                                }
                            }
                        </div>
                    </div>
                 }
            </div>
        </div>
    }
}

@functions{

    public static HtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if (cfg != null)
        {
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }
        }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new HtmlString(string.Join(" ", attrs));
    }
}

Lektion-6/Fixxo/Views/Partials/grid/bootstrap3.cshtml
@using System.Web
@using Microsoft.AspNetCore.Html
@using Newtonsoft.Json.Linq
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<dynamic>

@if (Model is JObject && Model?.sections is not null)
{
  var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;

    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections)
            {
                <div class="grid-section">
                    @foreach (var row in section.rows)
                    {
                        renderRow(row, true);
                    }
                </div>
            }
        }
        else
        {
            <div class="container">
                <div class="row clearfix">
                    @foreach (var sec in Model.sections)
                    {
                        <div class="grid-section">
                            <div class="col-md-@sec.grid column">
                                @foreach (var row in sec.rows)
                                {
                                    renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>
        }
    </div>
}

@functions{

    private async Task renderRow(dynamic row, bool singleColumn)
    {
        <div @RenderElementAttributes(row)>
            @if (singleColumn) {
                @:<div class="container">
            }
            <div class="row clearfix">
                @foreach (var area in row.areas)
                {
                    <div class="col-md-@area.grid column">
                        <div @RenderElementAttributes(area)>
                            @foreach (var control in area.controls)
                            {
                                if (control?.editor?.view != null)
                                {
                                    <text>@await Html.PartialAsync("grid/editors/base", (object)control)</text>
                                }
                            }
                        </div>
                    </div>
                 }
            </div>
            @if (singleColumn) {
                @:</div>
            }
        </div>
    }

}

@functions{

    public static HtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if (cfg != null)
        {
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }
        }

        JObject style = contentItem.styles;

        if (style != null)
        {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style=\"" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "\"");
        }

        return new HtmlString(string.Join(" ", attrs));
    }
}

Lektion-6/Fixxo/Views/Partials/grid/editors/base.cshtml
@model dynamic

@try
{
    string editor = EditorView(Model);
    <text>@await Html.PartialAsync(editor, Model as object)</text>
}
catch (Exception ex)
{
    <pre>@ex.ToString()</pre>
}

@functions{

    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.Replace(".html", ".cshtml");

        if (!view.Contains("/"))
        {
            view = "grid/editors/" + view;
        }

        return view;
    }
}

Lektion-6/Fixxo/Views/Partials/grid/editors/embed.cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<dynamic>

@if (Model is not null)
{
  string embedValue = Convert.ToString(Model.value);
  embedValue = embedValue.DetectIsJson() ? Model.value.preview : Model.value;

  <div class="video-wrapper">
    @Html.Raw(embedValue)
  </div>
}

Lektion-6/Fixxo/Views/Partials/grid/editors/macro.cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<dynamic>

@if (Model?.value is not null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    var parameters = new Dictionary<string,object>();
    foreach (var mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @await Umbraco.RenderMacroAsync(macroAlias, parameters)
    </text>
}

Lektion-6/Fixxo/Views/Partials/grid/editors/media.cshtml
@model dynamic
@using Umbraco.Cms.Core.Media
@using Umbraco.Cms.Core.PropertyEditors.ValueConverters
@inject IImageUrlGenerator ImageUrlGenerator

@if (Model?.value is not null)
{
    var url = Model.value.image;

    if (Model.editor.config != null && Model.editor.config.size != null)
    {
        if (Model.value.coordinates != null)
        {
            url = ImageCropperTemplateCoreExtensions.GetCropUrl(
                (string)url,
                ImageUrlGenerator,
                width: (int)Model.editor.config.size.width,
                height: (int)Model.editor.config.size.height,
                cropAlias: "default",
                cropDataSet: new ImageCropperValue
                {
                    Crops = new[]
                    {
                        new ImageCropperValue.ImageCropperCrop
                        {
                            Alias = "default",
                            Coordinates = new ImageCropperValue.ImageCropperCropCoordinates
                            {
                                X1 = (decimal)Model.value.coordinates.x1,
                                Y1 = (decimal)Model.value.coordinates.y1,
                                X2 = (decimal)Model.value.coordinates.x2,
                                Y2 = (decimal)Model.value.coordinates.y2
                            }
                        }
                    }
                });
        }
        else
        {
            url = ImageCropperTemplateCoreExtensions.GetCropUrl(
                (string)url,
                ImageUrlGenerator,
                width: (int)Model.editor.config.size.width,
                height: (int)Model.editor.config.size.height,
                cropDataSet: new ImageCropperValue
                {
                    FocalPoint = new ImageCropperValue.ImageCropperFocalPoint
                    {
                        Top = Model.value.focalPoint == null ? 0.5m : Model.value.focalPoint.top,
                        Left = Model.value.focalPoint == null ? 0.5m : Model.value.focalPoint.left
                    }
                });
        }
    }

    var altText = Model.value.altText ?? Model.value.caption ?? string.Empty;

    <img src="@url" alt="@altText">

    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

Lektion-6/Fixxo/Views/Partials/grid/editors/rte.cshtml
@using Umbraco.Cms.Core.Templates
@model dynamic
@inject HtmlLocalLinkParser HtmlLocalLinkParser;
@inject HtmlUrlParser HtmlUrlParser;
@inject HtmlImageSourceParser HtmlImageSourceParser;

@{
    var value = HtmlLocalLinkParser.EnsureInternalLinks(Model?.value.ToString());
    value = HtmlUrlParser.EnsureUrls(value);
    value = HtmlImageSourceParser.EnsureImageSources(value);
}

@Html.Raw(value)

Lektion-6/Fixxo/Views/Partials/grid/editors/textstring.cshtml
@model dynamic

@if (Model?.editor.config.markup is not null)
{
    string markup = Model.editor.config.markup.ToString();
    markup = markup.Replace("#value#", Html.ReplaceLineBreaks((string)Model.value.ToString()).ToString());

    if (Model.editor.config.style != null)
    {
        markup = markup.Replace("#style#", Model.editor.config.style.ToString());
    }

    <text>
        @Html.Raw(markup)
    </text>
}
else
{
    <text>
        <div style="@Model?.editor.config.style">@Model?.value</div>
    </text>
}